const { DynamoDBClient } = require('@aws-sdk/client-dynamodb');
const { DynamoDBDocumentClient, PutCommand } = require('@aws-sdk/lib-dynamodb');

const client = new DynamoDBClient({ region: 'eu-west-1' });
const docClient = DynamoDBDocumentClient.from(client);

const tableName = 'gymcoach-ai-main';

const defaultFoods = [
  {
    id: 'food-001',
    name: 'Chicken Breast',
    brand: 'Generic',
    category: 'Meat',
    subcategory: 'Poultry',
    nutritionFacts: {
      calories: 165,
      protein: 31,
      total_carbs: 0,
      total_fat: 3.6,
      dietary_fiber: 0,
      total_sugars: 0,
      sodium: 74,
    },
    serving_size: 100,
    serving_unit: 'g',
    commonServings: [
      {
        name: '100g',
        weight: 100,
        nutritionFacts: {
          calories: 165,
          protein: 31,
          total_carbs: 0,
          total_fat: 3.6,
          dietary_fiber: 0,
          total_sugars: 0,
          sodium: 74,
        },
      },
      {
        name: '1 breast',
        weight: 200,
        nutritionFacts: {
          calories: 330,
          protein: 62,
          total_carbs: 0,
          total_fat: 7.2,
          dietary_fiber: 0,
          total_sugars: 0,
          sodium: 148,
        },
      },
    ],
    allergens: [],
    dietaryTags: ['gluten-free', 'keto-friendly'],
    verified: true,
    isActive: true,
  },
  {
    id: 'food-002',
    name: 'Brown Rice',
    brand: 'Generic',
    category: 'Grains',
    subcategory: 'Rice',
    nutritionFacts: {
      calories: 111,
      protein: 2.6,
      total_carbs: 23,
      total_fat: 0.9,
      dietary_fiber: 1.8,
      total_sugars: 0.4,
      sodium: 5,
    },
    serving_size: 100,
    serving_unit: 'g',
    commonServings: [
      {
        name: '100g',
        weight: 100,
        nutritionFacts: {
          calories: 111,
          protein: 2.6,
          total_carbs: 23,
          total_fat: 0.9,
          dietary_fiber: 1.8,
          total_sugars: 0.4,
          sodium: 5,
        },
      },
      {
        name: '1 cup',
        weight: 195,
        nutritionFacts: {
          calories: 216,
          protein: 5,
          total_carbs: 45,
          total_fat: 1.8,
          dietary_fiber: 3.5,
          total_sugars: 0.8,
          sodium: 10,
        },
      },
    ],
    allergens: [],
    dietaryTags: ['vegan', 'gluten-free'],
    verified: true,
    isActive: true,
  },
  {
    id: 'food-003',
    name: 'Greek Yogurt',
    brand: 'Generic',
    category: 'Dairy',
    subcategory: 'Yogurt',
    nutritionFacts: {
      calories: 59,
      protein: 10,
      total_carbs: 3.6,
      total_fat: 0.4,
      dietary_fiber: 0,
      total_sugars: 3.6,
      sodium: 36,
    },
    serving_size: 100,
    serving_unit: 'g',
    commonServings: [
      {
        name: '100g',
        weight: 100,
        nutritionFacts: {
          calories: 59,
          protein: 10,
          total_carbs: 3.6,
          total_fat: 0.4,
          dietary_fiber: 0,
          total_sugars: 3.6,
          sodium: 36,
        },
      },
      {
        name: '1 cup',
        weight: 170,
        nutritionFacts: {
          calories: 100,
          protein: 17,
          total_carbs: 6,
          total_fat: 0.7,
          dietary_fiber: 0,
          total_sugars: 6,
          sodium: 61,
        },
      },
    ],
    allergens: ['milk'],
    dietaryTags: ['high-protein', 'low-fat'],
    verified: true,
    isActive: true,
  },
  {
    id: 'food-004',
    name: 'Salmon Fillet',
    brand: 'Generic',
    category: 'Seafood',
    subcategory: 'Fish',
    nutritionFacts: {
      calories: 208,
      protein: 22,
      total_carbs: 0,
      total_fat: 12,
      dietary_fiber: 0,
      total_sugars: 0,
      sodium: 59,
    },
    serving_size: 100,
    serving_unit: 'g',
    commonServings: [
      {
        name: '100g',
        weight: 100,
        nutritionFacts: {
          calories: 208,
          protein: 22,
          total_carbs: 0,
          total_fat: 12,
          dietary_fiber: 0,
          total_sugars: 0,
          sodium: 59,
        },
      },
      {
        name: '1 fillet',
        weight: 150,
        nutritionFacts: {
          calories: 312,
          protein: 33,
          total_carbs: 0,
          total_fat: 18,
          dietary_fiber: 0,
          total_sugars: 0,
          sodium: 89,
        },
      },
    ],
    allergens: ['fish'],
    dietaryTags: ['high-protein', 'omega-3', 'keto-friendly'],
    verified: true,
    isActive: true,
  },
  {
    id: 'food-005',
    name: 'Banana',
    brand: 'Generic',
    category: 'Fruits',
    subcategory: 'Tropical',
    nutritionFacts: {
      calories: 89,
      protein: 1.1,
      total_carbs: 23,
      total_fat: 0.3,
      dietary_fiber: 2.6,
      total_sugars: 12,
      sodium: 1,
    },
    serving_size: 100,
    serving_unit: 'g',
    commonServings: [
      {
        name: '100g',
        weight: 100,
        nutritionFacts: {
          calories: 89,
          protein: 1.1,
          total_carbs: 23,
          total_fat: 0.3,
          dietary_fiber: 2.6,
          total_sugars: 12,
          sodium: 1,
        },
      },
      {
        name: '1 medium',
        weight: 118,
        nutritionFacts: {
          calories: 105,
          protein: 1.3,
          total_carbs: 27,
          total_fat: 0.4,
          dietary_fiber: 3.1,
          total_sugars: 14,
          sodium: 1,
        },
      },
    ],
    allergens: [],
    dietaryTags: ['vegan', 'gluten-free', 'pre-workout'],
    verified: true,
    isActive: true,
  },
  {
    id: 'food-006',
    name: 'Oatmeal',
    brand: 'Generic',
    category: 'Grains',
    subcategory: 'Cereals',
    nutritionFacts: {
      calories: 68,
      protein: 2.4,
      total_carbs: 12,
      total_fat: 1.4,
      dietary_fiber: 1.7,
      total_sugars: 0.2,
      sodium: 4,
    },
    serving_size: 100,
    serving_unit: 'g',
    commonServings: [
      {
        name: '100g',
        weight: 100,
        nutritionFacts: {
          calories: 68,
          protein: 2.4,
          total_carbs: 12,
          total_fat: 1.4,
          dietary_fiber: 1.7,
          total_sugars: 0.2,
          sodium: 4,
        },
      },
      {
        name: '1 cup',
        weight: 81,
        nutritionFacts: {
          calories: 55,
          protein: 1.9,
          total_carbs: 10,
          total_fat: 1.1,
          dietary_fiber: 1.4,
          total_sugars: 0.2,
          sodium: 3,
        },
      },
    ],
    allergens: ['gluten'],
    dietaryTags: ['high-fiber', 'breakfast'],
    verified: true,
    isActive: true,
  },
  {
    id: 'food-007',
    name: 'Eggs',
    brand: 'Generic',
    category: 'Dairy',
    subcategory: 'Eggs',
    nutritionFacts: {
      calories: 155,
      protein: 13,
      total_carbs: 1.1,
      total_fat: 11,
      dietary_fiber: 0,
      total_sugars: 1.1,
      sodium: 124,
    },
    serving_size: 100,
    serving_unit: 'g',
    commonServings: [
      {
        name: '100g',
        weight: 100,
        nutritionFacts: {
          calories: 155,
          protein: 13,
          total_carbs: 1.1,
          total_fat: 11,
          dietary_fiber: 0,
          total_sugars: 1.1,
          sodium: 124,
        },
      },
      {
        name: '1 large',
        weight: 50,
        nutritionFacts: {
          calories: 78,
          protein: 6.5,
          total_carbs: 0.6,
          total_fat: 5.5,
          dietary_fiber: 0,
          total_sugars: 0.6,
          sodium: 62,
        },
      },
    ],
    allergens: ['eggs'],
    dietaryTags: ['high-protein', 'keto-friendly'],
    verified: true,
    isActive: true,
  },
  {
    id: 'food-008',
    name: 'Almonds',
    brand: 'Generic',
    category: 'Nuts',
    subcategory: 'Tree Nuts',
    nutritionFacts: {
      calories: 579,
      protein: 21,
      total_carbs: 22,
      total_fat: 50,
      dietary_fiber: 12,
      total_sugars: 4.4,
      sodium: 1,
    },
    serving_size: 100,
    serving_unit: 'g',
    commonServings: [
      {
        name: '100g',
        weight: 100,
        nutritionFacts: {
          calories: 579,
          protein: 21,
          total_carbs: 22,
          total_fat: 50,
          dietary_fiber: 12,
          total_sugars: 4.4,
          sodium: 1,
        },
      },
      {
        name: '1 oz',
        weight: 28,
        nutritionFacts: {
          calories: 162,
          protein: 6,
          total_carbs: 6,
          total_fat: 14,
          dietary_fiber: 3.4,
          total_sugars: 1.2,
          sodium: 0,
        },
      },
    ],
    allergens: ['tree-nuts'],
    dietaryTags: ['vegan', 'high-protein', 'healthy-fats'],
    verified: true,
    isActive: true,
  },
  // VEGETABLES
  {
    id: 'food-009',
    name: 'Broccoli',
    brand: 'Generic',
    category: 'Vegetables',
    subcategory: 'Cruciferous',
    nutritionFacts: {
      calories: 34,
      protein: 2.8,
      total_carbs: 7,
      total_fat: 0.4,
      dietary_fiber: 2.6,
      total_sugars: 1.5,
      sodium: 33,
    },
    serving_size: 100,
    serving_unit: 'g',
    commonServings: [
      {
        name: '100g',
        weight: 100,
        nutritionFacts: {
          calories: 34,
          protein: 2.8,
          total_carbs: 7,
          total_fat: 0.4,
          dietary_fiber: 2.6,
          total_sugars: 1.5,
          sodium: 33,
        },
      },
      {
        name: '1 cup chopped',
        weight: 91,
        nutritionFacts: {
          calories: 31,
          protein: 2.5,
          total_carbs: 6,
          total_fat: 0.4,
          dietary_fiber: 2.4,
          total_sugars: 1.4,
          sodium: 30,
        },
      },
    ],
    allergens: [],
    dietaryTags: ['vegan', 'low-calorie', 'high-fiber'],
    verified: true,
    isActive: true,
  },
  {
    id: 'food-010',
    name: 'Spinach',
    brand: 'Generic',
    category: 'Vegetables',
    subcategory: 'Leafy Greens',
    nutritionFacts: {
      calories: 23,
      protein: 2.9,
      total_carbs: 3.6,
      total_fat: 0.4,
      dietary_fiber: 2.2,
      total_sugars: 0.4,
      sodium: 79,
    },
    serving_size: 100,
    serving_unit: 'g',
    commonServings: [
      {
        name: '100g',
        weight: 100,
        nutritionFacts: {
          calories: 23,
          protein: 2.9,
          total_carbs: 3.6,
          total_fat: 0.4,
          dietary_fiber: 2.2,
          total_sugars: 0.4,
          sodium: 79,
        },
      },
      {
        name: '1 cup raw',
        weight: 30,
        nutritionFacts: {
          calories: 7,
          protein: 0.9,
          total_carbs: 1.1,
          total_fat: 0.1,
          dietary_fiber: 0.7,
          total_sugars: 0.1,
          sodium: 24,
        },
      },
    ],
    allergens: [],
    dietaryTags: ['vegan', 'low-calorie', 'iron-rich'],
    verified: true,
    isActive: true,
  },
  {
    id: 'food-011',
    name: 'Sweet Potato',
    brand: 'Generic',
    category: 'Vegetables',
    subcategory: 'Root Vegetables',
    nutritionFacts: {
      calories: 86,
      protein: 1.6,
      total_carbs: 20,
      total_fat: 0.1,
      dietary_fiber: 3,
      total_sugars: 4.2,
      sodium: 54,
    },
    serving_size: 100,
    serving_unit: 'g',
    commonServings: [
      {
        name: '100g',
        weight: 100,
        nutritionFacts: {
          calories: 86,
          protein: 1.6,
          total_carbs: 20,
          total_fat: 0.1,
          dietary_fiber: 3,
          total_sugars: 4.2,
          sodium: 54,
        },
      },
      {
        name: '1 medium',
        weight: 128,
        nutritionFacts: {
          calories: 110,
          protein: 2,
          total_carbs: 26,
          total_fat: 0.1,
          dietary_fiber: 3.8,
          total_sugars: 5.4,
          sodium: 69,
        },
      },
    ],
    allergens: [],
    dietaryTags: ['vegan', 'high-fiber', 'beta-carotene'],
    verified: true,
    isActive: true,
  },
  {
    id: 'food-012',
    name: 'Bell Pepper',
    brand: 'Generic',
    category: 'Vegetables',
    subcategory: 'Peppers',
    nutritionFacts: {
      calories: 31,
      protein: 1,
      total_carbs: 7,
      total_fat: 0.3,
      dietary_fiber: 2.5,
      total_sugars: 4.2,
      sodium: 4,
    },
    serving_size: 100,
    serving_unit: 'g',
    commonServings: [
      {
        name: '100g',
        weight: 100,
        nutritionFacts: {
          calories: 31,
          protein: 1,
          total_carbs: 7,
          total_fat: 0.3,
          dietary_fiber: 2.5,
          total_sugars: 4.2,
          sodium: 4,
        },
      },
      {
        name: '1 medium',
        weight: 119,
        nutritionFacts: {
          calories: 37,
          protein: 1.2,
          total_carbs: 8,
          total_fat: 0.4,
          dietary_fiber: 3,
          total_sugars: 5,
          sodium: 5,
        },
      },
    ],
    allergens: [],
    dietaryTags: ['vegan', 'low-calorie', 'vitamin-c'],
    verified: true,
    isActive: true,
  },
  // MORE FRUITS
  {
    id: 'food-013',
    name: 'Apple',
    brand: 'Generic',
    category: 'Fruits',
    subcategory: 'Pome',
    nutritionFacts: {
      calories: 52,
      protein: 0.3,
      total_carbs: 14,
      total_fat: 0.2,
      dietary_fiber: 2.4,
      total_sugars: 10,
      sodium: 1,
    },
    serving_size: 100,
    serving_unit: 'g',
    commonServings: [
      {
        name: '100g',
        weight: 100,
        nutritionFacts: {
          calories: 52,
          protein: 0.3,
          total_carbs: 14,
          total_fat: 0.2,
          dietary_fiber: 2.4,
          total_sugars: 10,
          sodium: 1,
        },
      },
      {
        name: '1 medium',
        weight: 182,
        nutritionFacts: {
          calories: 95,
          protein: 0.5,
          total_carbs: 25,
          total_fat: 0.3,
          dietary_fiber: 4.4,
          total_sugars: 19,
          sodium: 2,
        },
      },
    ],
    allergens: [],
    dietaryTags: ['vegan', 'high-fiber', 'antioxidants'],
    verified: true,
    isActive: true,
  },
  {
    id: 'food-014',
    name: 'Blueberries',
    brand: 'Generic',
    category: 'Fruits',
    subcategory: 'Berries',
    nutritionFacts: {
      calories: 57,
      protein: 0.7,
      total_carbs: 14,
      total_fat: 0.3,
      dietary_fiber: 2.4,
      total_sugars: 10,
      sodium: 1,
    },
    serving_size: 100,
    serving_unit: 'g',
    commonServings: [
      {
        name: '100g',
        weight: 100,
        nutritionFacts: {
          calories: 57,
          protein: 0.7,
          total_carbs: 14,
          total_fat: 0.3,
          dietary_fiber: 2.4,
          total_sugars: 10,
          sodium: 1,
        },
      },
      {
        name: '1 cup',
        weight: 148,
        nutritionFacts: {
          calories: 84,
          protein: 1.1,
          total_carbs: 21,
          total_fat: 0.5,
          dietary_fiber: 3.6,
          total_sugars: 15,
          sodium: 1,
        },
      },
    ],
    allergens: [],
    dietaryTags: ['vegan', 'antioxidants', 'low-calorie'],
    verified: true,
    isActive: true,
  },
  {
    id: 'food-015',
    name: 'Avocado',
    brand: 'Generic',
    category: 'Fruits',
    subcategory: 'Tropical',
    nutritionFacts: {
      calories: 160,
      protein: 2,
      total_carbs: 9,
      total_fat: 15,
      dietary_fiber: 7,
      total_sugars: 0.7,
      sodium: 7,
    },
    serving_size: 100,
    serving_unit: 'g',
    commonServings: [
      {
        name: '100g',
        weight: 100,
        nutritionFacts: {
          calories: 160,
          protein: 2,
          total_carbs: 9,
          total_fat: 15,
          dietary_fiber: 7,
          total_sugars: 0.7,
          sodium: 7,
        },
      },
      {
        name: '1 medium',
        weight: 150,
        nutritionFacts: {
          calories: 240,
          protein: 3,
          total_carbs: 13,
          total_fat: 22,
          dietary_fiber: 10,
          total_sugars: 1,
          sodium: 10,
        },
      },
    ],
    allergens: [],
    dietaryTags: ['vegan', 'healthy-fats', 'keto-friendly'],
    verified: true,
    isActive: true,
  },
  // MORE PROTEINS
  {
    id: 'food-016',
    name: 'Ground Beef',
    brand: 'Generic',
    category: 'Meat',
    subcategory: 'Beef',
    nutritionFacts: {
      calories: 250,
      protein: 26,
      total_carbs: 0,
      total_fat: 15,
      dietary_fiber: 0,
      total_sugars: 0,
      sodium: 75,
    },
    serving_size: 100,
    serving_unit: 'g',
    commonServings: [
      {
        name: '100g',
        weight: 100,
        nutritionFacts: {
          calories: 250,
          protein: 26,
          total_carbs: 0,
          total_fat: 15,
          dietary_fiber: 0,
          total_sugars: 0,
          sodium: 75,
        },
      },
      {
        name: '1 patty',
        weight: 85,
        nutritionFacts: {
          calories: 213,
          protein: 22,
          total_carbs: 0,
          total_fat: 13,
          dietary_fiber: 0,
          total_sugars: 0,
          sodium: 64,
        },
      },
    ],
    allergens: [],
    dietaryTags: ['high-protein', 'keto-friendly', 'iron-rich'],
    verified: true,
    isActive: true,
  },
  {
    id: 'food-017',
    name: 'Turkey Breast',
    brand: 'Generic',
    category: 'Meat',
    subcategory: 'Poultry',
    nutritionFacts: {
      calories: 135,
      protein: 30,
      total_carbs: 0,
      total_fat: 1,
      dietary_fiber: 0,
      total_sugars: 0,
      sodium: 1040,
    },
    serving_size: 100,
    serving_unit: 'g',
    commonServings: [
      {
        name: '100g',
        weight: 100,
        nutritionFacts: {
          calories: 135,
          protein: 30,
          total_carbs: 0,
          total_fat: 1,
          dietary_fiber: 0,
          total_sugars: 0,
          sodium: 1040,
        },
      },
      {
        name: '3 slices',
        weight: 56,
        nutritionFacts: {
          calories: 76,
          protein: 17,
          total_carbs: 0,
          total_fat: 0.6,
          dietary_fiber: 0,
          total_sugars: 0,
          sodium: 582,
        },
      },
    ],
    allergens: [],
    dietaryTags: ['high-protein', 'low-fat', 'lean'],
    verified: true,
    isActive: true,
  },
  {
    id: 'food-018',
    name: 'Tuna',
    brand: 'Generic',
    category: 'Seafood',
    subcategory: 'Fish',
    nutritionFacts: {
      calories: 144,
      protein: 30,
      total_carbs: 0,
      total_fat: 1,
      dietary_fiber: 0,
      total_sugars: 0,
      sodium: 43,
    },
    serving_size: 100,
    serving_unit: 'g',
    commonServings: [
      {
        name: '100g',
        weight: 100,
        nutritionFacts: {
          calories: 144,
          protein: 30,
          total_carbs: 0,
          total_fat: 1,
          dietary_fiber: 0,
          total_sugars: 0,
          sodium: 43,
        },
      },
      {
        name: '1 can',
        weight: 85,
        nutritionFacts: {
          calories: 122,
          protein: 25,
          total_carbs: 0,
          total_fat: 0.9,
          dietary_fiber: 0,
          total_sugars: 0,
          sodium: 37,
        },
      },
    ],
    allergens: ['fish'],
    dietaryTags: ['high-protein', 'low-fat', 'omega-3'],
    verified: true,
    isActive: true,
  },
  {
    id: 'food-019',
    name: 'Tofu',
    brand: 'Generic',
    category: 'Plant Protein',
    subcategory: 'Soy',
    nutritionFacts: {
      calories: 76,
      protein: 8,
      total_carbs: 2,
      total_fat: 5,
      dietary_fiber: 0.3,
      total_sugars: 0.6,
      sodium: 7,
    },
    serving_size: 100,
    serving_unit: 'g',
    commonServings: [
      {
        name: '100g',
        weight: 100,
        nutritionFacts: {
          calories: 76,
          protein: 8,
          total_carbs: 2,
          total_fat: 5,
          dietary_fiber: 0.3,
          total_sugars: 0.6,
          sodium: 7,
        },
      },
      {
        name: '1/2 cup',
        weight: 126,
        nutritionFacts: {
          calories: 96,
          protein: 10,
          total_carbs: 2.5,
          total_fat: 6,
          dietary_fiber: 0.4,
          total_sugars: 0.8,
          sodium: 9,
        },
      },
    ],
    allergens: ['soy'],
    dietaryTags: ['vegan', 'plant-protein', 'low-carb'],
    verified: true,
    isActive: true,
  },
  // LEGUMES & BEANS
  {
    id: 'food-020',
    name: 'Black Beans',
    brand: 'Generic',
    category: 'Legumes',
    subcategory: 'Beans',
    nutritionFacts: {
      calories: 132,
      protein: 9,
      total_carbs: 24,
      total_fat: 0.5,
      dietary_fiber: 9,
      total_sugars: 0.3,
      sodium: 2,
    },
    serving_size: 100,
    serving_unit: 'g',
    commonServings: [
      {
        name: '100g',
        weight: 100,
        nutritionFacts: {
          calories: 132,
          protein: 9,
          total_carbs: 24,
          total_fat: 0.5,
          dietary_fiber: 9,
          total_sugars: 0.3,
          sodium: 2,
        },
      },
      {
        name: '1 cup',
        weight: 172,
        nutritionFacts: {
          calories: 227,
          protein: 15,
          total_carbs: 41,
          total_fat: 0.9,
          dietary_fiber: 15,
          total_sugars: 0.5,
          sodium: 3,
        },
      },
    ],
    allergens: [],
    dietaryTags: ['vegan', 'high-fiber', 'plant-protein'],
    verified: true,
    isActive: true,
  },
  {
    id: 'food-021',
    name: 'Lentils',
    brand: 'Generic',
    category: 'Legumes',
    subcategory: 'Lentils',
    nutritionFacts: {
      calories: 116,
      protein: 9,
      total_carbs: 20,
      total_fat: 0.4,
      dietary_fiber: 8,
      total_sugars: 1.8,
      sodium: 2,
    },
    serving_size: 100,
    serving_unit: 'g',
    commonServings: [
      {
        name: '100g',
        weight: 100,
        nutritionFacts: {
          calories: 116,
          protein: 9,
          total_carbs: 20,
          total_fat: 0.4,
          dietary_fiber: 8,
          total_sugars: 1.8,
          sodium: 2,
        },
      },
      {
        name: '1 cup',
        weight: 198,
        nutritionFacts: {
          calories: 230,
          protein: 18,
          total_carbs: 40,
          total_fat: 0.8,
          dietary_fiber: 16,
          total_sugars: 3.6,
          sodium: 4,
        },
      },
    ],
    allergens: [],
    dietaryTags: ['vegan', 'high-fiber', 'plant-protein'],
    verified: true,
    isActive: true,
  },
  // MORE DAIRY
  {
    id: 'food-022',
    name: 'Milk',
    brand: 'Generic',
    category: 'Dairy',
    subcategory: 'Milk',
    nutritionFacts: {
      calories: 42,
      protein: 3.4,
      total_carbs: 5,
      total_fat: 1,
      dietary_fiber: 0,
      total_sugars: 5,
      sodium: 44,
    },
    serving_size: 100,
    serving_unit: 'g',
    commonServings: [
      {
        name: '100ml',
        weight: 100,
        nutritionFacts: {
          calories: 42,
          protein: 3.4,
          total_carbs: 5,
          total_fat: 1,
          dietary_fiber: 0,
          total_sugars: 5,
          sodium: 44,
        },
      },
      {
        name: '1 cup',
        weight: 244,
        nutritionFacts: {
          calories: 102,
          protein: 8,
          total_carbs: 12,
          total_fat: 2.4,
          dietary_fiber: 0,
          total_sugars: 12,
          sodium: 107,
        },
      },
    ],
    allergens: ['milk'],
    dietaryTags: ['calcium-rich', 'protein'],
    verified: true,
    isActive: true,
  },
  {
    id: 'food-023',
    name: 'Cheddar Cheese',
    brand: 'Generic',
    category: 'Dairy',
    subcategory: 'Cheese',
    nutritionFacts: {
      calories: 403,
      protein: 25,
      total_carbs: 1.3,
      total_fat: 33,
      dietary_fiber: 0,
      total_sugars: 0.5,
      sodium: 621,
    },
    serving_size: 100,
    serving_unit: 'g',
    commonServings: [
      {
        name: '100g',
        weight: 100,
        nutritionFacts: {
          calories: 403,
          protein: 25,
          total_carbs: 1.3,
          total_fat: 33,
          dietary_fiber: 0,
          total_sugars: 0.5,
          sodium: 621,
        },
      },
      {
        name: '1 slice',
        weight: 28,
        nutritionFacts: {
          calories: 113,
          protein: 7,
          total_carbs: 0.4,
          total_fat: 9,
          dietary_fiber: 0,
          total_sugars: 0.1,
          sodium: 174,
        },
      },
    ],
    allergens: ['milk'],
    dietaryTags: ['high-protein', 'keto-friendly', 'calcium-rich'],
    verified: true,
    isActive: true,
  },
  // MORE GRAINS
  {
    id: 'food-024',
    name: 'Quinoa',
    brand: 'Generic',
    category: 'Grains',
    subcategory: 'Ancient Grains',
    nutritionFacts: {
      calories: 120,
      protein: 4.4,
      total_carbs: 22,
      total_fat: 1.9,
      dietary_fiber: 2.8,
      total_sugars: 0.9,
      sodium: 7,
    },
    serving_size: 100,
    serving_unit: 'g',
    commonServings: [
      {
        name: '100g',
        weight: 100,
        nutritionFacts: {
          calories: 120,
          protein: 4.4,
          total_carbs: 22,
          total_fat: 1.9,
          dietary_fiber: 2.8,
          total_sugars: 0.9,
          sodium: 7,
        },
      },
      {
        name: '1 cup',
        weight: 185,
        nutritionFacts: {
          calories: 222,
          protein: 8,
          total_carbs: 39,
          total_fat: 3.6,
          dietary_fiber: 5.2,
          total_sugars: 1.6,
          sodium: 13,
        },
      },
    ],
    allergens: [],
    dietaryTags: ['vegan', 'complete-protein', 'gluten-free'],
    verified: true,
    isActive: true,
  },
  {
    id: 'food-025',
    name: 'Whole Wheat Bread',
    brand: 'Generic',
    category: 'Grains',
    subcategory: 'Bread',
    nutritionFacts: {
      calories: 247,
      protein: 13,
      total_carbs: 41,
      total_fat: 4,
      dietary_fiber: 6,
      total_sugars: 6,
      sodium: 400,
    },
    serving_size: 100,
    serving_unit: 'g',
    commonServings: [
      {
        name: '100g',
        weight: 100,
        nutritionFacts: {
          calories: 247,
          protein: 13,
          total_carbs: 41,
          total_fat: 4,
          dietary_fiber: 6,
          total_sugars: 6,
          sodium: 400,
        },
      },
      {
        name: '1 slice',
        weight: 28,
        nutritionFacts: {
          calories: 69,
          protein: 3.6,
          total_carbs: 11,
          total_fat: 1.1,
          dietary_fiber: 1.7,
          total_sugars: 1.7,
          sodium: 112,
        },
      },
    ],
    allergens: ['gluten', 'wheat'],
    dietaryTags: ['high-fiber', 'whole-grain'],
    verified: true,
    isActive: true,
  },
  // MORE NUTS & SEEDS
  {
    id: 'food-026',
    name: 'Walnuts',
    brand: 'Generic',
    category: 'Nuts',
    subcategory: 'Tree Nuts',
    nutritionFacts: {
      calories: 654,
      protein: 15,
      total_carbs: 14,
      total_fat: 65,
      dietary_fiber: 7,
      total_sugars: 2.6,
      sodium: 2,
    },
    serving_size: 100,
    serving_unit: 'g',
    commonServings: [
      {
        name: '100g',
        weight: 100,
        nutritionFacts: {
          calories: 654,
          protein: 15,
          total_carbs: 14,
          total_fat: 65,
          dietary_fiber: 7,
          total_sugars: 2.6,
          sodium: 2,
        },
      },
      {
        name: '1 oz',
        weight: 28,
        nutritionFacts: {
          calories: 183,
          protein: 4.3,
          total_carbs: 3.9,
          total_fat: 18,
          dietary_fiber: 1.9,
          total_sugars: 0.7,
          sodium: 1,
        },
      },
    ],
    allergens: ['tree-nuts'],
    dietaryTags: ['vegan', 'healthy-fats', 'omega-3'],
    verified: true,
    isActive: true,
  },
  {
    id: 'food-027',
    name: 'Chia Seeds',
    brand: 'Generic',
    category: 'Seeds',
    subcategory: 'Seeds',
    nutritionFacts: {
      calories: 486,
      protein: 17,
      total_carbs: 42,
      total_fat: 31,
      dietary_fiber: 34,
      total_sugars: 0,
      sodium: 16,
    },
    serving_size: 100,
    serving_unit: 'g',
    commonServings: [
      {
        name: '100g',
        weight: 100,
        nutritionFacts: {
          calories: 486,
          protein: 17,
          total_carbs: 42,
          total_fat: 31,
          dietary_fiber: 34,
          total_sugars: 0,
          sodium: 16,
        },
      },
      {
        name: '1 tbsp',
        weight: 12,
        nutritionFacts: {
          calories: 58,
          protein: 2,
          total_carbs: 5,
          total_fat: 3.7,
          dietary_fiber: 4.1,
          total_sugars: 0,
          sodium: 2,
        },
      },
    ],
    allergens: [],
    dietaryTags: ['vegan', 'high-fiber', 'omega-3', 'superfood'],
    verified: true,
    isActive: true,
  },
  // SNACKS & OTHERS
  {
    id: 'food-028',
    name: 'Dark Chocolate',
    brand: 'Generic',
    category: 'Snacks',
    subcategory: 'Chocolate',
    nutritionFacts: {
      calories: 546,
      protein: 8,
      total_carbs: 46,
      total_fat: 38,
      dietary_fiber: 11,
      total_sugars: 30,
      sodium: 20,
    },
    serving_size: 100,
    serving_unit: 'g',
    commonServings: [
      {
        name: '100g',
        weight: 100,
        nutritionFacts: {
          calories: 546,
          protein: 8,
          total_carbs: 46,
          total_fat: 38,
          dietary_fiber: 11,
          total_sugars: 30,
          sodium: 20,
        },
      },
      {
        name: '1 square',
        weight: 10,
        nutritionFacts: {
          calories: 55,
          protein: 0.8,
          total_carbs: 4.6,
          total_fat: 3.8,
          dietary_fiber: 1.1,
          total_sugars: 3,
          sodium: 2,
        },
      },
    ],
    allergens: ['milk'],
    dietaryTags: ['antioxidants', 'magnesium'],
    verified: true,
    isActive: true,
  },
  {
    id: 'food-029',
    name: 'Olive Oil',
    brand: 'Generic',
    category: 'Oils',
    subcategory: 'Cooking Oil',
    nutritionFacts: {
      calories: 884,
      protein: 0,
      total_carbs: 0,
      total_fat: 100,
      dietary_fiber: 0,
      total_sugars: 0,
      sodium: 2,
    },
    serving_size: 100,
    serving_unit: 'g',
    commonServings: [
      {
        name: '100ml',
        weight: 100,
        nutritionFacts: {
          calories: 884,
          protein: 0,
          total_carbs: 0,
          total_fat: 100,
          dietary_fiber: 0,
          total_sugars: 0,
          sodium: 2,
        },
      },
      {
        name: '1 tbsp',
        weight: 14,
        nutritionFacts: {
          calories: 124,
          protein: 0,
          total_carbs: 0,
          total_fat: 14,
          dietary_fiber: 0,
          total_sugars: 0,
          sodium: 0,
        },
      },
    ],
    allergens: [],
    dietaryTags: ['vegan', 'healthy-fats', 'keto-friendly'],
    verified: true,
    isActive: true,
  },
  {
    id: 'food-030',
    name: 'White Rice',
    brand: 'Generic',
    category: 'Grains',
    subcategory: 'Rice',
    nutritionFacts: {
      calories: 130,
      protein: 2.7,
      total_carbs: 28,
      total_fat: 0.3,
      dietary_fiber: 0.4,
      total_sugars: 0.1,
      sodium: 5,
    },
    serving_size: 100,
    serving_unit: 'g',
    commonServings: [
      {
        name: '100g',
        weight: 100,
        nutritionFacts: {
          calories: 130,
          protein: 2.7,
          total_carbs: 28,
          total_fat: 0.3,
          dietary_fiber: 0.4,
          total_sugars: 0.1,
          sodium: 5,
        },
      },
      {
        name: '1 cup',
        weight: 158,
        nutritionFacts: {
          calories: 205,
          protein: 4.3,
          total_carbs: 44,
          total_fat: 0.4,
          dietary_fiber: 0.6,
          total_sugars: 0.1,
          sodium: 8,
        },
      },
    ],
    allergens: [],
    dietaryTags: ['vegan', 'gluten-free'],
    verified: true,
    isActive: true,
  },
  // Snacks & International Foods
  {
    id: 'food-031',
    name: 'Hummus',
    brand: 'Generic',
    category: 'Legumes',
    subcategory: 'Spread',
    nutritionFacts: {
      calories: 166,
      protein: 7.9,
      total_carbs: 14.3,
      total_fat: 9.6,
      dietary_fiber: 6,
      total_sugars: 0.3,
      sodium: 378,
    },
    serving_size: 100,
    serving_unit: 'g',
    commonServings: [
      {
        name: '100g',
        weight: 100,
        nutritionFacts: {
          calories: 166,
          protein: 7.9,
          total_carbs: 14.3,
          total_fat: 9.6,
          dietary_fiber: 6,
          total_sugars: 0.3,
          sodium: 378,
        },
      },
      {
        name: '2 tbsp',
        weight: 30,
        nutritionFacts: {
          calories: 50,
          protein: 2.4,
          total_carbs: 4.3,
          total_fat: 2.9,
          dietary_fiber: 1.8,
          total_sugars: 0.1,
          sodium: 113,
        },
      },
    ],
    allergens: ['sesame'],
    dietaryTags: ['vegan', 'plant-protein', 'mediterranean'],
    verified: true,
    isActive: true,
  },
  {
    id: 'food-032',
    name: 'Peanut Butter',
    brand: 'Generic',
    category: 'Nuts',
    subcategory: 'Spread',
    nutritionFacts: {
      calories: 588,
      protein: 25,
      total_carbs: 20,
      total_fat: 50,
      dietary_fiber: 6,
      total_sugars: 9,
      sodium: 17,
    },
    serving_size: 100,
    serving_unit: 'g',
    commonServings: [
      {
        name: '100g',
        weight: 100,
        nutritionFacts: {
          calories: 588,
          protein: 25,
          total_carbs: 20,
          total_fat: 50,
          dietary_fiber: 6,
          total_sugars: 9,
          sodium: 17,
        },
      },
      {
        name: '2 tbsp',
        weight: 32,
        nutritionFacts: {
          calories: 188,
          protein: 8,
          total_carbs: 6,
          total_fat: 16,
          dietary_fiber: 2,
          total_sugars: 3,
          sodium: 5,
        },
      },
    ],
    allergens: ['peanuts'],
    dietaryTags: ['vegan', 'plant-protein', 'healthy-fats'],
    verified: true,
    isActive: true,
  },
  {
    id: 'food-033',
    name: 'Cottage Cheese',
    brand: 'Generic',
    category: 'Dairy',
    subcategory: 'Cheese',
    nutritionFacts: {
      calories: 98,
      protein: 11,
      total_carbs: 3.4,
      total_fat: 4.3,
      dietary_fiber: 0,
      total_sugars: 2.7,
      sodium: 364,
    },
    serving_size: 100,
    serving_unit: 'g',
    commonServings: [
      {
        name: '100g',
        weight: 100,
        nutritionFacts: {
          calories: 98,
          protein: 11,
          total_carbs: 3.4,
          total_fat: 4.3,
          dietary_fiber: 0,
          total_sugars: 2.7,
          sodium: 364,
        },
      },
      {
        name: '1/2 cup',
        weight: 110,
        nutritionFacts: {
          calories: 108,
          protein: 12,
          total_carbs: 3.7,
          total_fat: 4.7,
          dietary_fiber: 0,
          total_sugars: 3,
          sodium: 400,
        },
      },
    ],
    allergens: ['milk'],
    dietaryTags: ['high-protein', 'low-fat'],
    verified: true,
    isActive: true,
  },
  {
    id: 'food-034',
    name: 'Pasta (Cooked)',
    brand: 'Generic',
    category: 'Grains',
    subcategory: 'Pasta',
    nutritionFacts: {
      calories: 131,
      protein: 5,
      total_carbs: 25,
      total_fat: 1.1,
      dietary_fiber: 1.4,
      total_sugars: 0.8,
      sodium: 1,
    },
    serving_size: 100,
    serving_unit: 'g',
    commonServings: [
      {
        name: '100g',
        weight: 100,
        nutritionFacts: {
          calories: 131,
          protein: 5,
          total_carbs: 25,
          total_fat: 1.1,
          dietary_fiber: 1.4,
          total_sugars: 0.8,
          sodium: 1,
        },
      },
      {
        name: '1 cup',
        weight: 140,
        nutritionFacts: {
          calories: 184,
          protein: 7,
          total_carbs: 35,
          total_fat: 1.5,
          dietary_fiber: 2,
          total_sugars: 1,
          sodium: 2,
        },
      },
    ],
    allergens: ['gluten', 'wheat'],
    dietaryTags: ['high-carb', 'vegetarian'],
    verified: true,
    isActive: true,
  },
  {
    id: 'food-035',
    name: 'Orange',
    brand: 'Generic',
    category: 'Fruits',
    subcategory: 'Citrus',
    nutritionFacts: {
      calories: 47,
      protein: 0.9,
      total_carbs: 12,
      total_fat: 0.1,
      dietary_fiber: 2.4,
      total_sugars: 9,
      sodium: 0,
    },
    serving_size: 100,
    serving_unit: 'g',
    commonServings: [
      {
        name: '100g',
        weight: 100,
        nutritionFacts: {
          calories: 47,
          protein: 0.9,
          total_carbs: 12,
          total_fat: 0.1,
          dietary_fiber: 2.4,
          total_sugars: 9,
          sodium: 0,
        },
      },
      {
        name: '1 medium',
        weight: 131,
        nutritionFacts: {
          calories: 62,
          protein: 1.2,
          total_carbs: 15,
          total_fat: 0.2,
          dietary_fiber: 3.1,
          total_sugars: 12,
          sodium: 0,
        },
      },
    ],
    allergens: [],
    dietaryTags: ['vegan', 'vitamin-c', 'antioxidants'],
    verified: true,
    isActive: true,
  },
  {
    id: 'food-036',
    name: 'Strawberries',
    brand: 'Generic',
    category: 'Fruits',
    subcategory: 'Berries',
    nutritionFacts: {
      calories: 32,
      protein: 0.7,
      total_carbs: 7.7,
      total_fat: 0.3,
      dietary_fiber: 2,
      total_sugars: 4.9,
      sodium: 1,
    },
    serving_size: 100,
    serving_unit: 'g',
    commonServings: [
      {
        name: '100g',
        weight: 100,
        nutritionFacts: {
          calories: 32,
          protein: 0.7,
          total_carbs: 7.7,
          total_fat: 0.3,
          dietary_fiber: 2,
          total_sugars: 4.9,
          sodium: 1,
        },
      },
      {
        name: '1 cup',
        weight: 152,
        nutritionFacts: {
          calories: 49,
          protein: 1,
          total_carbs: 12,
          total_fat: 0.4,
          dietary_fiber: 3,
          total_sugars: 7,
          sodium: 2,
        },
      },
    ],
    allergens: [],
    dietaryTags: ['vegan', 'antioxidants', 'low-calorie'],
    verified: true,
    isActive: true,
  },
  // Beverages
  {
    id: 'food-037',
    name: 'Black Coffee',
    brand: 'Generic',
    category: 'Beverages',
    subcategory: 'Coffee',
    nutritionFacts: {
      calories: 1,
      protein: 0.1,
      total_carbs: 0,
      total_fat: 0,
      dietary_fiber: 0,
      total_sugars: 0,
      sodium: 5,
    },
    serving_size: 100,
    serving_unit: 'g',
    commonServings: [
      {
        name: '1 cup',
        weight: 240,
        nutritionFacts: {
          calories: 2,
          protein: 0.3,
          total_carbs: 0,
          total_fat: 0,
          dietary_fiber: 0,
          total_sugars: 0,
          sodium: 10,
        },
      },
    ],
    allergens: [],
    dietaryTags: ['vegan', 'zero-calorie', 'caffeine'],
    verified: true,
    isActive: true,
  },
  {
    id: 'food-038',
    name: 'Green Tea',
    brand: 'Generic',
    category: 'Beverages',
    subcategory: 'Tea',
    nutritionFacts: {
      calories: 0,
      protein: 0,
      total_carbs: 0,
      total_fat: 0,
      dietary_fiber: 0,
      total_sugars: 0,
      sodium: 0,
    },
    serving_size: 100,
    serving_unit: 'g',
    commonServings: [
      {
        name: '1 cup',
        weight: 240,
        nutritionFacts: {
          calories: 0,
          protein: 0,
          total_carbs: 0,
          total_fat: 0,
          dietary_fiber: 0,
          total_sugars: 0,
          sodium: 0,
        },
      },
    ],
    allergens: [],
    dietaryTags: ['vegan', 'zero-calorie', 'antioxidants'],
    verified: true,
    isActive: true,
  },
  // Additional Popular Foods
  {
    id: 'food-039',
    name: 'Carrots',
    brand: 'Generic',
    category: 'Vegetables',
    subcategory: 'Root Vegetables',
    nutritionFacts: {
      calories: 41,
      protein: 0.9,
      total_carbs: 10,
      total_fat: 0.2,
      dietary_fiber: 2.8,
      total_sugars: 4.7,
      sodium: 69,
    },
    serving_size: 100,
    serving_unit: 'g',
    commonServings: [
      {
        name: '100g',
        weight: 100,
        nutritionFacts: {
          calories: 41,
          protein: 0.9,
          total_carbs: 10,
          total_fat: 0.2,
          dietary_fiber: 2.8,
          total_sugars: 4.7,
          sodium: 69,
        },
      },
      {
        name: '1 medium',
        weight: 61,
        nutritionFacts: {
          calories: 25,
          protein: 0.5,
          total_carbs: 6,
          total_fat: 0.1,
          dietary_fiber: 1.7,
          total_sugars: 2.9,
          sodium: 42,
        },
      },
    ],
    allergens: [],
    dietaryTags: ['vegan', 'low-calorie', 'beta-carotene'],
    verified: true,
    isActive: true,
  },
  {
    id: 'food-040',
    name: 'Cucumber',
    brand: 'Generic',
    category: 'Vegetables',
    subcategory: 'Gourds',
    nutritionFacts: {
      calories: 16,
      protein: 0.7,
      total_carbs: 4,
      total_fat: 0.1,
      dietary_fiber: 0.5,
      total_sugars: 1.7,
      sodium: 2,
    },
    serving_size: 100,
    serving_unit: 'g',
    commonServings: [
      {
        name: '100g',
        weight: 100,
        nutritionFacts: {
          calories: 16,
          protein: 0.7,
          total_carbs: 4,
          total_fat: 0.1,
          dietary_fiber: 0.5,
          total_sugars: 1.7,
          sodium: 2,
        },
      },
      {
        name: '1 cup sliced',
        weight: 119,
        nutritionFacts: {
          calories: 19,
          protein: 0.8,
          total_carbs: 5,
          total_fat: 0.1,
          dietary_fiber: 0.6,
          total_sugars: 2,
          sodium: 2,
        },
      },
    ],
    allergens: [],
    dietaryTags: ['vegan', 'low-calorie', 'hydrating'],
    verified: true,
    isActive: true,
  },
  {
    id: 'food-041',
    name: 'Tomato',
    brand: 'Generic',
    category: 'Vegetables',
    subcategory: 'Nightshades',
    nutritionFacts: {
      calories: 18,
      protein: 0.9,
      total_carbs: 3.9,
      total_fat: 0.2,
      dietary_fiber: 1.2,
      total_sugars: 2.6,
      sodium: 5,
    },
    serving_size: 100,
    serving_unit: 'g',
    commonServings: [
      {
        name: '100g',
        weight: 100,
        nutritionFacts: {
          calories: 18,
          protein: 0.9,
          total_carbs: 3.9,
          total_fat: 0.2,
          dietary_fiber: 1.2,
          total_sugars: 2.6,
          sodium: 5,
        },
      },
      {
        name: '1 medium',
        weight: 123,
        nutritionFacts: {
          calories: 22,
          protein: 1.1,
          total_carbs: 4.8,
          total_fat: 0.2,
          dietary_fiber: 1.5,
          total_sugars: 3.2,
          sodium: 6,
        },
      },
    ],
    allergens: [],
    dietaryTags: ['vegan', 'low-calorie', 'lycopene'],
    verified: true,
    isActive: true,
  },
  {
    id: 'food-042',
    name: 'Potato',
    brand: 'Generic',
    category: 'Vegetables',
    subcategory: 'Root Vegetables',
    nutritionFacts: {
      calories: 77,
      protein: 2,
      total_carbs: 17,
      total_fat: 0.1,
      dietary_fiber: 2.2,
      total_sugars: 0.8,
      sodium: 6,
    },
    serving_size: 100,
    serving_unit: 'g',
    commonServings: [
      {
        name: '100g',
        weight: 100,
        nutritionFacts: {
          calories: 77,
          protein: 2,
          total_carbs: 17,
          total_fat: 0.1,
          dietary_fiber: 2.2,
          total_sugars: 0.8,
          sodium: 6,
        },
      },
      {
        name: '1 medium',
        weight: 173,
        nutritionFacts: {
          calories: 133,
          protein: 3.5,
          total_carbs: 29,
          total_fat: 0.2,
          dietary_fiber: 3.8,
          total_sugars: 1.4,
          sodium: 10,
        },
      },
    ],
    allergens: [],
    dietaryTags: ['vegan', 'gluten-free', 'potassium-rich'],
    verified: true,
    isActive: true,
  },
  {
    id: 'food-043',
    name: 'Onion',
    brand: 'Generic',
    category: 'Vegetables',
    subcategory: 'Alliums',
    nutritionFacts: {
      calories: 40,
      protein: 1.1,
      total_carbs: 9.3,
      total_fat: 0.1,
      dietary_fiber: 1.7,
      total_sugars: 4.2,
      sodium: 4,
    },
    serving_size: 100,
    serving_unit: 'g',
    commonServings: [
      {
        name: '100g',
        weight: 100,
        nutritionFacts: {
          calories: 40,
          protein: 1.1,
          total_carbs: 9.3,
          total_fat: 0.1,
          dietary_fiber: 1.7,
          total_sugars: 4.2,
          sodium: 4,
        },
      },
      {
        name: '1 medium',
        weight: 110,
        nutritionFacts: {
          calories: 44,
          protein: 1.2,
          total_carbs: 10,
          total_fat: 0.1,
          dietary_fiber: 1.9,
          total_sugars: 4.6,
          sodium: 4,
        },
      },
    ],
    allergens: [],
    dietaryTags: ['vegan', 'low-calorie', 'antioxidants'],
    verified: true,
    isActive: true,
  },
  // More Proteins
  {
    id: 'food-044',
    name: 'Chicken Thigh',
    brand: 'Generic',
    category: 'Meat',
    subcategory: 'Poultry',
    nutritionFacts: {
      calories: 209,
      protein: 26,
      total_carbs: 0,
      total_fat: 11,
      dietary_fiber: 0,
      total_sugars: 0,
      sodium: 77,
    },
    serving_size: 100,
    serving_unit: 'g',
    commonServings: [
      {
        name: '100g',
        weight: 100,
        nutritionFacts: {
          calories: 209,
          protein: 26,
          total_carbs: 0,
          total_fat: 11,
          dietary_fiber: 0,
          total_sugars: 0,
          sodium: 77,
        },
      },
      {
        name: '1 thigh',
        weight: 52,
        nutritionFacts: {
          calories: 109,
          protein: 13.5,
          total_carbs: 0,
          total_fat: 5.7,
          dietary_fiber: 0,
          total_sugars: 0,
          sodium: 40,
        },
      },
    ],
    allergens: [],
    dietaryTags: ['high-protein', 'keto-friendly'],
    verified: true,
    isActive: true,
  },
  {
    id: 'food-045',
    name: 'Cod Fillet',
    brand: 'Generic',
    category: 'Seafood',
    subcategory: 'Fish',
    nutritionFacts: {
      calories: 82,
      protein: 18,
      total_carbs: 0,
      total_fat: 0.7,
      dietary_fiber: 0,
      total_sugars: 0,
      sodium: 54,
    },
    serving_size: 100,
    serving_unit: 'g',
    commonServings: [
      {
        name: '100g',
        weight: 100,
        nutritionFacts: {
          calories: 82,
          protein: 18,
          total_carbs: 0,
          total_fat: 0.7,
          dietary_fiber: 0,
          total_sugars: 0,
          sodium: 54,
        },
      },
      {
        name: '1 fillet',
        weight: 180,
        nutritionFacts: {
          calories: 148,
          protein: 32,
          total_carbs: 0,
          total_fat: 1.3,
          dietary_fiber: 0,
          total_sugars: 0,
          sodium: 97,
        },
      },
    ],
    allergens: ['fish'],
    dietaryTags: ['high-protein', 'low-fat', 'lean'],
    verified: true,
    isActive: true,
  },
  {
    id: 'food-046',
    name: 'Shrimp',
    brand: 'Generic',
    category: 'Seafood',
    subcategory: 'Shellfish',
    nutritionFacts: {
      calories: 99,
      protein: 18,
      total_carbs: 0.9,
      total_fat: 1.7,
      dietary_fiber: 0,
      total_sugars: 0,
      sodium: 111,
    },
    serving_size: 100,
    serving_unit: 'g',
    commonServings: [
      {
        name: '100g',
        weight: 100,
        nutritionFacts: {
          calories: 99,
          protein: 18,
          total_carbs: 0.9,
          total_fat: 1.7,
          dietary_fiber: 0,
          total_sugars: 0,
          sodium: 111,
        },
      },
      {
        name: '3 oz',
        weight: 85,
        nutritionFacts: {
          calories: 84,
          protein: 15,
          total_carbs: 0.8,
          total_fat: 1.4,
          dietary_fiber: 0,
          total_sugars: 0,
          sodium: 94,
        },
      },
    ],
    allergens: ['shellfish'],
    dietaryTags: ['high-protein', 'low-fat', 'low-carb'],
    verified: true,
    isActive: true,
  },
  {
    id: 'food-047',
    name: 'Pork Chop',
    brand: 'Generic',
    category: 'Meat',
    subcategory: 'Pork',
    nutritionFacts: {
      calories: 231,
      protein: 23,
      total_carbs: 0,
      total_fat: 15,
      dietary_fiber: 0,
      total_sugars: 0,
      sodium: 53,
    },
    serving_size: 100,
    serving_unit: 'g',
    commonServings: [
      {
        name: '100g',
        weight: 100,
        nutritionFacts: {
          calories: 231,
          protein: 23,
          total_carbs: 0,
          total_fat: 15,
          dietary_fiber: 0,
          total_sugars: 0,
          sodium: 53,
        },
      },
      {
        name: '1 chop',
        weight: 85,
        nutritionFacts: {
          calories: 196,
          protein: 19.5,
          total_carbs: 0,
          total_fat: 12.8,
          dietary_fiber: 0,
          total_sugars: 0,
          sodium: 45,
        },
      },
    ],
    allergens: [],
    dietaryTags: ['high-protein', 'keto-friendly'],
    verified: true,
    isActive: true,
  },
  // More Fruits
  {
    id: 'food-048',
    name: 'Grapes',
    brand: 'Generic',
    category: 'Fruits',
    subcategory: 'Berries',
    nutritionFacts: {
      calories: 62,
      protein: 0.6,
      total_carbs: 16,
      total_fat: 0.2,
      dietary_fiber: 0.9,
      total_sugars: 16,
      sodium: 2,
    },
    serving_size: 100,
    serving_unit: 'g',
    commonServings: [
      {
        name: '100g',
        weight: 100,
        nutritionFacts: {
          calories: 62,
          protein: 0.6,
          total_carbs: 16,
          total_fat: 0.2,
          dietary_fiber: 0.9,
          total_sugars: 16,
          sodium: 2,
        },
      },
      {
        name: '1 cup',
        weight: 151,
        nutritionFacts: {
          calories: 94,
          protein: 0.9,
          total_carbs: 24,
          total_fat: 0.3,
          dietary_fiber: 1.4,
          total_sugars: 24,
          sodium: 3,
        },
      },
    ],
    allergens: [],
    dietaryTags: ['vegan', 'antioxidants', 'resveratrol'],
    verified: true,
    isActive: true,
  },
  {
    id: 'food-049',
    name: 'Pineapple',
    brand: 'Generic',
    category: 'Fruits',
    subcategory: 'Tropical',
    nutritionFacts: {
      calories: 50,
      protein: 0.5,
      total_carbs: 13,
      total_fat: 0.1,
      dietary_fiber: 1.4,
      total_sugars: 10,
      sodium: 1,
    },
    serving_size: 100,
    serving_unit: 'g',
    commonServings: [
      {
        name: '100g',
        weight: 100,
        nutritionFacts: {
          calories: 50,
          protein: 0.5,
          total_carbs: 13,
          total_fat: 0.1,
          dietary_fiber: 1.4,
          total_sugars: 10,
          sodium: 1,
        },
      },
      {
        name: '1 cup chunks',
        weight: 165,
        nutritionFacts: {
          calories: 83,
          protein: 0.8,
          total_carbs: 21,
          total_fat: 0.2,
          dietary_fiber: 2.3,
          total_sugars: 16,
          sodium: 2,
        },
      },
    ],
    allergens: [],
    dietaryTags: ['vegan', 'vitamin-c', 'bromelain'],
    verified: true,
    isActive: true,
  },
  {
    id: 'food-050',
    name: 'Watermelon',
    brand: 'Generic',
    category: 'Fruits',
    subcategory: 'Melons',
    nutritionFacts: {
      calories: 30,
      protein: 0.6,
      total_carbs: 8,
      total_fat: 0.2,
      dietary_fiber: 0.4,
      total_sugars: 6,
      sodium: 1,
    },
    serving_size: 100,
    serving_unit: 'g',
    commonServings: [
      {
        name: '100g',
        weight: 100,
        nutritionFacts: {
          calories: 30,
          protein: 0.6,
          total_carbs: 8,
          total_fat: 0.2,
          dietary_fiber: 0.4,
          total_sugars: 6,
          sodium: 1,
        },
      },
      {
        name: '1 cup diced',
        weight: 152,
        nutritionFacts: {
          calories: 46,
          protein: 0.9,
          total_carbs: 12,
          total_fat: 0.2,
          dietary_fiber: 0.6,
          total_sugars: 9,
          sodium: 2,
        },
      },
    ],
    allergens: [],
    dietaryTags: ['vegan', 'low-calorie', 'hydrating'],
    verified: true,
    isActive: true,
  },
];

async function populateFoods() {
  console.log('Starting to populate foods...');

  for (const food of defaultFoods) {
    const nameLower = food.name.toLowerCase();
    const item = {
      PK: `FOOD#${food.id}`,
      SK: `FOOD#${food.id}`,
      GSI1PK: 'FOOD',
      GSI1SK: `${nameLower}#${food.id}`,
      EntityType: 'FOOD',
      FoodId: food.id,
      Name: food.name,
      NameLower: nameLower,
      Brand: food.brand,
      Category: JSON.stringify(food.category),
      Subcategory: food.subcategory,
      NutritionFacts: JSON.stringify(food.nutritionFacts),
      ServingSize: food.serving_size,
      ServingUnit: food.serving_unit,
      CommonServings: JSON.stringify(food.commonServings),
      Allergens: JSON.stringify(food.allergens),
      DietaryTags: JSON.stringify(food.dietaryTags),
      Verified: food.verified,
      IsActive: food.isActive,
      CreatedAt: new Date().toISOString(),
      UpdatedAt: new Date().toISOString(),
    };

    try {
      await docClient.send(
        new PutCommand({
          TableName: tableName,
          Item: item,
        })
      );
      console.log(`✅ Added food: ${food.name}`);
    } catch (error) {
      console.error(`❌ Failed to add food ${food.name}:`, error);
    }
  }

  console.log('✅ Food population completed!');
}

populateFoods().catch(console.error);
