[package]
name = "lambda-router"
version = "0.1.0"
edition = "2021"
description = "A lightweight, Express-like REST API routing framework for AWS Lambda"
license = "MIT"

[lib]
name = "lambda_router"
path = "src/lib.rs"

[dependencies]
lambda_runtime = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["rt", "macros"] }
anyhow = "1.0"
thiserror = "1.0"
regex = "1.10"
lazy_static = "1.4"
async-trait = "0.1"
futures = "0.3"

[dev-dependencies]
tokio-test = "0.4"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
